### ISSUE TITLE
Bug: "(en blanco)" category in excel (both row and column)

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#54]
It is not really important, but if there is time we should correct it.

**Comment by rmartinsanta** [comment]
This happens because the pivot table range takes the whole columns, instead of choosing only the rows where there is data. By selecting data this way, if the user adds extra rows to the raw data sheet, the Pivot Table and all calculated fields can be automatically recalculated.

In Java calculation mode, "(en blanco)" / "blank" does not appear because ranges are known before hand and therefore fixed.

The most likely solution is filtering in the pivot table to ignore blank/empty tags, but I haven't found a way to set column/row filters in the pivot table filter using Apache POI. Any help is appreciated.
