### ISSUE TITLE
Missing way of adding the paper results

### ISSUE THREAD

**Issue by ea2809** [rmartinsanta/mork#73]
There should be a way of adding the paper's results.

**Comment by rmartinsanta** [comment]
Functionality already exists but was not documented, I have added a new page in the documentation detailing how to use it.
Please, take a look and reopen the issue is the documentation is not clear enough, and consider opening a PR with any suggestion to improve it 😃 

https://mork-optimization.readthedocs.io/en/latest/features/compare/
